LOGGER:
    level: "DEBUG"
    dir: "./logs/"
    file: "log.txt"

TOOL:
  COMMON:
    output_download_url_prefix: "https://mollyseek.com/downloads/"
    markdown_download_url_prefix: "https://try.mollyseek.cn/backend/markdown_download?file_path="
    handle_tool_input_output_url: "http://120.79.142.227:60718/backend/handle_tool_input_output"
  NETMHCPAN:   
    url: "http://3.34.237.164:60823/netmhcpan"
    netmhcpan_dir: "/mnt/softwares/netMHCpan-4.1/Linux_x86_64"
    input_tmp_netmhcpan_dir: "/mnt/tmp/NetMHCpan/input"
    output_tmp_netmhcpan_dir: "/mnt/tmp/NetMHCpan/output"
  ESM:
    output_tmp_mse3_dir: "/mnt/tmp/ESM3"
  NETMHCSTABPAN:   
    url: "http://3.34.237.164:60823/netmhcstabpan"
    netmhcstabpan_dir: "/mnt/softwares/netMHCstabpan-1.0/Linux_x86_64"
    input_tmp_netmhcstabpan_dir: "/mnt/tmp/NetMHCstabpan/input"
    output_tmp_netmhcstabpan_dir: "/mnt/tmp/NetMHCstabpan/output"
  PMTNET:
    url: "http://3.34.237.164:60825/pMTnet"
    pMTnet_env_python_dir: "/mnt/softwares/miniconda3/envs/pmtnet/bin/python"
    pMTnet_script_dir: "/mnt/softwares/pMTnet/pMTnet.py"
    library_dir: "/mnt/softwares/pMTnet/library"
    input_tmp_pmtnet_dir: "/mnt/tmp/pmtnet/input"
    output_tmp_pmtnet_dir: "/mnt/tmp/pmtnet/output"
    upload_dir: "/mnt/tmp/pmtnet/upload"
    download_dir: "/mnt/tmp/pmtnet/download"
  EXTRACT_PEPTIDE:
    tmp_extract_peptide_dir: "/mnt/tmp/ExtractPeptide/output"
  NETCHOP:
    url: "http://3.34.237.164:60823/netchop"
    netchop_dir: "/mnt/softwares/netchop-3.1/Linux_x86_64"
    input_tmp_netchop_dir: "/mnt/tmp/NetChop/input"
    output_tmp_netchop_dir: "/mnt/tmp/NetChop/output"
  PRIME:
    url: "http://3.34.237.164:60823/prime"
    input_tmp_prime_dir: "/mnt/tmp/Prime/input"
    output_tmp_prime_dir: "/mnt/tmp/Prime/output"
  NETTCR:
    url: "http://3.34.237.164:60823/nettcr"
    nettcr_dir: "/mnt/softwares/NetTCR-2.2"  
    input_tmp_nettcr_dir: "/mnt/tmp/NetTCR/input"
    output_tmp_nettcr_dir: "/mnt/tmp/NetTCR/output"    
  NETCTLPAN:
    url: "http://3.34.237.164:60823/netctlpan"
    netctlpan_dir: /mnt/softwares/netCTLpan-1.1
    input_tmp_netctlpan_dir: /mnt/tmp/netctlpan/input
    output_tmp_netctlpan_dir: /mnt/tmp/netctlpan/output
  PISTE:
    url: "http://3.34.237.164:60825/piste"
    piste_env_python_dir: /mnt/softwares/miniconda3/envs/piste/bin/python
    input_tmp_piste_dir: /mnt/tmp/piste/input
    output_tmp_piste_dir: /mnt/tmp/piste/output
  IMMUNEAPP:
    url: "http://3.34.237.164:60824/ImmuneApp"
    script_path: /mnt/softwares/ImmuneApp/ImmuneApp_presentation_prediction.py
    python_bin: /mnt/softwares/miniconda3/envs/ImmuneApp/bin/python
    input_tmp_dir: /mnt/tmp/immuneapp/input  
    output_tmp_dir: /mnt/tmp/immuneapp/output
  IMMUNEAPP_NEO:
    url: "http://3.34.237.164:60824/ImmuneApp_Neo"
    script_path: /mnt/softwares/ImmuneApp/ImmuneApp_immunogenicity_prediction.py
    python_bin: /mnt/softwares/miniconda3/envs/ImmuneApp/bin/python
    input_tmp_dir: /mnt/tmp/immuneapp_neo/input  
    output_tmp_dir: /mnt/tmp/immuneapp_neo/output
  BIGMHC:
    url: "http://3.34.237.164:60823/bigmhc"
    bigmhc_dir: "/mnt/softwares/bigmhc/src"  
    input_tmp_bigmhc_dir: "/mnt/tmp/BigMHC/input"
    output_tmp_bigmhc_dir: "/mnt/tmp/BigMHC/output" 
  TRANSPHLA:
    url: "http://3.34.237.164:60824/TransPHLA_AOMP"
    script_path: /mnt/softwares/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py
    python_bin: /mnt/softwares/miniconda3/envs/transphla/bin/python
    hla_peptide_mapping_path: src/model/agents/tools/TransPHLA/TransPHLA_hla_peptide_mapping.json
    input_tmp_dir: /mnt/tmp/transphla/input
    output_tmp_dir: /mnt/tmp/transphla/output
  UNIPMT:
    script_path: "/mnt/softwares/UniPMT/code/main.py"
    python_bin: "/mnt/softwares/miniconda3/envs/unipmt/bin/python"
    input_tmp_dir: "/mnt/tmp/UniPMT/input"
    output_tmp_dir: "/mnt/tmp/UniPMT/output"
    nodes_peptides_csv: "/mnt/softwares/UniPMT/data/pmt_pmt/nodes_peptides.csv"
    nodes_mhc_csv: "/mnt/softwares/UniPMT/data/pmt_pmt/nodes_mhc.csv"
    nodes_tcr_csv: "/mnt/softwares/UniPMT/data/pmt_pmt/nodes_tcr.csv"
    p_features_path: "/mnt/softwares/UniPMT/data/pmt_pmt/meta/p_features.npy"
    t_features_path: "/mnt/softwares/UniPMT/data/pmt_pmt/meta/t_features.npy"
    m_features_path: "/mnt/softwares/UniPMT/data/pmt_pmt/meta/m_features.npy"
    unipmt_input_file_path: "/mnt/softwares/UniPMT/data/pmt_pmt/meta"
  NETCHOP_CLEAVAGE:
    input_tmp_dir: "/mnt/tmp/NetChop_Cleavage/input"
    output_tmp_dir: "/mnt/tmp/NetChop_Cleavage/output"
  NEOANTIGEN_SELECTION:
    bind_level_alternative: ["<= SB", "<= WB"]  # 如果只需要 "<= SB"
    # bind_level_alternative: ["<= SB", "<= WB"]  # 如果需要 "<= SB" 或 "<= WB"
    netctlpan_threshold: 0.0
    bigmhc_el_threshold: 0.0    #100
    bigmhc_im_threshold: 0.0  #100
    pmtnet_rank: 0.1           #100
    rnafold_energy_threshold : 0.0

  LINEARDESIGN:
    url: "http://3.34.237.164:60824/LinearDesign"
    script: "/mnt/softwares/LinearDesign/linear_design.py"
    input_tmp_dir: "/mnt/tmp/LinearDesign/input"
    output_tmp_dir: "/mnt/tmp/LinearDesign/output"

  RNAFOLD:
    url: "http://3.34.237.164:60823/rnafold"
    input_tmp_dir: "/mnt/tmp/rnafold/input" 
    output_tmp_dir: "/mnt/tmp/rnafold/output"

  RNAPLOT:
    url: "http://3.34.237.164:60823/rnaplot"
    input_tmp_dir: "/mnt/tmp/rnaplot/input" 
    output_tmp_dir: "/mnt/tmp/rnaplot/output"


  NEOMRNA_SELECTION:
    input_tmp_dir: "/mnt/tmp/neomrnaselection/input"
    output_tmp_dir: "/mnt/tmp/neomrnaselection/output"
    cleavage_enhancer: "RKKRRQRRR" 
    spacer: "UUAUUAUUUAUUUAUUUAUUUAUUUAUUUA"
    5_UTR: "TCAAGCTTTTGGACCCTCGTACAGAAGCTAATACGACTCACTAT"
    3_UTR: "AGCCACCATGGCACAAGTCATTAATACAAACAGCCTGTCGCTG
            TTGACCCAGAATAACCTGAACAAATCCCAGTCCGCACTGGGCA
            CTGCTATCGAGCGTTTGTCTTCCGGTCTGCGTATCAACAGCGCG
            AAAGACGATGCGGCAGGACAGGCGATTGCTAACCGTTTTACCG
            CGAACATCAAAGGTCTGACTCAGGCTTCCCGTAACGCTAACGA
            CGGTATCTCCATTGCGCAGACCACTGAAGGCGCGCTGAACGAA
            ATCAACAACAACCTGCAGCGTGTGCGTGAACTGGCGGTTCAGT
            CTGCGAATGGTACTAACTCCCAGTCTGACCTCGACTCCATCCAG
            GCTGAAATCACCCAGCGCCTGAACGAAATCGACCGTGTATCCG
            GCCAGACTCAGTTCAACGGCGTGAAAGTCCTGGCGCAGGACAA
            CACCCTGACCATCCAGGTTGGTGCCAACGACGGTGAAACTATC
            GATATTGATTTAAAAGAAATCAGCTCTAAAACACTGGGACTTG
            ATAAGCTTAATGTCCAAGATGCCTACACCCCGAAAGAAACTGC
            TGTAACCGTTGATAAAACTACCTATAAAAATGGTACAGATCCT
            ATTACAGCCCAGAGCAATACTGATATCCAAACTGCAATTGGCG
            GTGGTGCAACGGGGGTTACTGGGGCTGATATCAAATTTAAAGA
            TGGTCAATACTATTTAGATGTTAAAGGCGGTGCTTCTGCTGGTG
            TTTATAAAGCCACTTATGATGAAACTACAAAGAAAGTTAATAT
            TGATACGACTGATAAAACTCCGTTGGCAACTGCGGAAGCTACA
            GCTATTCGGGGAACGGCCACTATAACCCACAACCAAATTGCTG
            AAGTAACAAAAGAGGGTGTTGATACGACCACAGTTGCGGCTCA
            ACTTGCTGCAGCAGGGGTTACTGGCGCCGATAAGGACAATACT
            AGCCTTGTAAAACTATCGTTTGAGGATAAAAACGGTAAGGTTA
            TTGATGGTGGCTATGCAGTGAAAATGGGCGACGATTTCTATGC
            CGCTACATATGATGAGAAAACAGGTGCAATTACTGCTAAAACC
            ACTACTTATACAGATGGTACTGGCGTTGCTCAAACTGGAGCTGT
            GAAATTTGGTGGCGCAAATGGTAAATCTGAAGTTGTTACTGCT
            ACCGATGGTAAGACTTACTTAGCAAGCGACCTTGACAAACATA
            ACTTCAGAACAGGCGGTGAGCTTAAAGAGGTTAATACAGATAA
            GACTGAAAACCCACTGCAGAAAATTGATGCTGCCTTGGCACAG
            GTTGATACACTTCGTTCTGACCTGGGTGCGGTTCAGAACCGTTT
            CAACTCCGCTATCACCAACCTGGGCAATACCGTAAATAACCTG
            TCTTCTGCCCGTAGCCGTATCGAAGATTCCGACTACGCAACCGA
            AGTCTCCAACATGTCTCGCGCGCAGATTCTGCAGCAGGCCGGT
            ACCTCCGTTCTGGCGCAGGCGAACCAGGTTCCGCAAAACGTCC
            TCTCTTTACTGCGTTGATAATAGGCTGGAGCCTCGGTGGCCATG
            CTTCTTGCCCCTTGGGCCTCCCCCCAGCCCCTCCTCCCCTTCCTG
            CACCCGTACCCCCGTGGTCTTTGAATAAAGTCTGAGTGGGCGGC"
            
    IRES: "GGCCACCATGGCACAAGTCATTAATACAAACAGCCTGTCGCTG
          TTGACCCAGAATAACCTGAACAAATCCCAGTCCGCACTGGGCA
          CTGCTATCGAGCGTTTGTCTTCCGGTCTGCGTATCAACAGCGCG
          AAAGACGATGCGGCAGGACAGGCGATTGCTAACCGTTTTACCG
          CGAACATCAAAGGTCTGACTCAGGCTTCCCGTAACGCTAACGA
          CGGTATCTCCATTGCGCAGACCACTGAAGGCGCGCTGAACGAA
          ATCAACAACAACCTGCAGCGTGTGCGTGAACTGGCGGTTCAGT
          CTGCGAATGGTACTAACTCCCAGTCTGACCTCGACTCCATCCAG
          GCTGAAATCACCCAGCGCCTGAACGAAATCGACCGTGTATCCG
          GCCAGACTCAGTTCAACGGCGTGAAAGTCCTGGCGCAGGACAA
          CACCCTGACCATCCAGGTTGGTGCCAACGACGGTGAAACTATC
          GATATTGATTTAAAAGAAATCAGCTCTAAAACACTGGGACTTG
          ATAAGCTTAATGTCCAAGATGCCTACACCCCGAAAGAAACTGC
          TGTAACCGTTGATAAAACTACCTATAAAAATGGTACAGATCCT
          ATTACAGCCCAGAGCAATACTGATATCCAAACTGCAATTGGCG
          GTGGTGCAACGGGGGTTACTGGGGCTGATATCAAATTTAAAGA
          TGGTCAATACTATTTAGATGTTAAAGGCGGTGCTTCTGCTGGTG
          TTTATAAAGCCACTTATGATGAAACTACAAAGAAAGTTAATAT
          TGATACGACTGATAAAACTCCGTTGGCAACTGCGGAAGCTACA
          GCTATTCGGGGAACGGCCACTATAACCCACAACCAAATTGCTG
          AAGTAACAAAAGAGGGTGTTGATACGACCACAGTTGCGGCTCA
          ACTTGCTGCAGCAGGGGTTACTGGCGCCGATAAGGACAATACT
          AGCCTTGTAAAACTATCGTTTGAGGATAAAAACGGTAAGGTTA
          TTGATGGTGGCTATGCAGTGAAAATGGGCGACGATTTCTATGC
          CGCTACATATGATGAGAAAACAGGTGCAATTACTGCTAAAACC
          ACTACTTATACAGATGGTACTGGCGTTGCTCAAACTGGAGCTGT
          GAAATTTGGTGGCGCAAATGGTAAATCTGAAGTTGTTACTGCT
          ACCGATGGTAAGACTTACTTAGCAAGCGACCTTGACAAACATA
          ACTTCAGAACAGGCGGTGAGCTTAAAGAGGTTAATACAGATAA
          GACTGAAAACCCACTGCAGAAAATTGATGCTGCCTTGGCACAG
          GTTGATACACTTCGTTCTGACCTGGGTGCGGTTCAGAACCGTTT
          CAACTCCGCTATCACCAACCTGGGCAATACCGTAAATAACCTG
          TCTTCTGCCCGTAGCCGTATCGAAGATTCCGACTACGCAACCGA
          AGTCTCCAACATGTCTCGCGCGCAGATTCTGCAGCAGGCCGGT
          ACCTCCGTTCTGGCGCAGGCGAACCAGGTTCCGCAAAACGTCC
          TCTCTTTACTGCGTTGATAATAGGCTGGAGCCTCGGTGGCCATG
          CTTCTTGCCCCTTGGGCCTCCCCCCAGCCCCTCCTCCCCTTCCTG
          CACCCGTACCCCCGTGGTCTTTGAATAAAGTCTGAGTGGGCGGC"

MINIO:
  endpoint: "47.237.170.62:18080"
  molly_bucket: "molly"
  netmhcpan_bucket: "netmhcpan-results"
  esm_bucket: "esm3-results"
  netmhcstabpan_bucket: "netmhcstabpan-results"
  pmtnet_bucket: "pmtnet-results"
  extract_peptide_bucket: "extract-peptide-results"
  netchop_bucket: "netchop-results"
  prime_bucket: "prime-results"
  nettcr_bucket: "nettcr-results"
  netctlpan_bucket: "netctlpan-results"
  piste_bucket: "piste-results"
  immuneapp_bucket: "immuneapp-results"
  immuneapp_neo_bucket: "immuneapp-neo-results"
  bigmhc_bucket: "bigmhc-results"
  transphla_bucket: "transphla-results"
  unipmt_bucket: "unipmt-results"
  netchop_cleavage_bucket: "netchop-cleavage-results"
  rnafold_bucket: "rnafold-results"
  lineardesign_bucket: "lineardesign-results"
  rnaplot_bucket: "rnaplot-results"
  secure: false

AGENT:
  checkpoint_db_name: "mrna_predict_agent.sqlite"

RAG:
  theory_server_url: "http://52.74.25.27:60820/query/stream"
  case_server_url: "http://3.34.237.164:60820/query/stream"
  files_path: "/mnt/workspace/dev/ljs/lightrag/theory_rag/files_md"

MD2PDF:
  watermark_content: "mRNANeo.com"
  header_content: "复旦大学 NEO 项目"
  css_path: "./src/utils/data/style.css"
  logo_path: "./src/utils/data/neo.jpg"
  temp_file: "/mnt/data/temp"
