LOGGER:
    level: "DEBUG"
    dir: "./logs/"
    file: "log.txt"

TOOL:
  COMMON:
    output_download_url_prefix: "https://mollyseek.com/downloads/"
  NETMHCPAN:   
    netmhcpan_dir: "/mnt/softwares/netMHCpan-4.1/Linux_x86_64"
    input_tmp_netmhcpan_dir: "/mnt/tmp/NetMHCpan/input"
    output_tmp_netmhcpan_dir: "/mnt/tmp/NetMHCpan/output"
  ESM:
    output_tmp_mse3_dir: "/mnt/tmp/ESM3"
  NETMHCSTABPAN:   
    netmhcstabpan_dir: "/mnt/softwares/netMHCstabpan-1.0/Linux_x86_64"
    input_tmp_netmhcstabpan_dir: "/mnt/tmp/NetMHCstabpan/input"
    output_tmp_netmhcstabpan_dir: "/mnt/tmp/NetMHCstabpan/output"
 

MINIO:
  endpoint: "localhost:18080"
  netmhcpan_bucket: "NetMHCpan-results"
  esm_bucket: "ESM3-results"
  netmhcstabpan_bucket: "NetMHCstabpan-results"
  secure: false

