LOGGER:
    level: "DEBUG"
    dir: "/mnt/workspace/stg/ljs/new/mRNAPredictionAgent/logs/"
    file: "log.txt"

LLM:
    model_name: "gpt-4o"
    temperature: 0.1

TOOL:
    upload_dir: "/mnt/tmp/files/"
