LOGGER:
    level: "DEBUG"
    dir: "./logs/"
    file: "log.txt"

TOOL:
  COMMON:
    output_download_url_prefix: "https://mollyseek.com/downloads/"
  NETMHCPAN:   
    netmhcpan_dir: "/mnt/softwares/netMHCpan-4.1/Linux_x86_64"
    input_tmp_netmhcpan_dir: "/mnt/tmp/NetMHCpan/input"
    output_tmp_netmhcpan_dir: "/mnt/tmp/NetMHCpan/output"
  ESM:
    output_tmp_mse3_dir: "/mnt/tmp/ESM3"
  NETMHCSTABPAN:   
    netmhcstabpan_dir: "/mnt/softwares/netMHCstabpan-1.0/Linux_x86_64"
    input_tmp_netmhcstabpan_dir: "/mnt/tmp/NetMHCstabpan/input"
    output_tmp_netmhcstabpan_dir: "/mnt/tmp/NetMHCstabpan/output"
  PMTNET:
    pMTnet_env_python_dir: "/mnt/softwares/miniconda3/envs/pmtnet/bin/python"
    pMTnet_script_dir: "/mnt/softwares/pMTnet/pMTnet.py"
    library_dir: "/mnt/softwares/pMTnet/library"
    input_tmp_pmtnet_dir: "/mnt/tmp/pMtNet/input"
    output_tmp_pmtnet_dir: "/mnt/tmp/pmtnet/output"
  EXTRACT_PEPTIDE:
    tmp_extract_peptide_dir: "/mnt/tmp/ExtractPeptide/output"
  NETCTLPAN:
    netctlpan_dir: /mnt/softwares/netCTLpan-1.1
    input_tmp_netctlpan_dir: /mnt/tmp/netctlpan/input
    output_tmp_netctlpan_dir: /mnt/tmp/netctlpan/output
  PISTE:
    piste_env_python_dir: /mnt/softwares/miniconda3/envs/piste/bin/python
    output_tmp_piste_dir: /mnt/tmp/piste/output


 

MINIO:
  endpoint: "localhost:18080"
  netmhcpan_bucket: "netmhcpan-results"
  esm_bucket: "esm3-results"
  netmhcstabpan_bucket: "netmhcstabpan-results"
  pmtnet_bucket: "pmtnet-results"
  extract_peptide_bucket: "extract-peptide-results"
  netctlpan_bucket: "netctlpan-results"
  piste_bucket: "piste-results"
  secure: false
