LOGGER:
    level: "DEBUG"
    dir: "./logs/"
    file: "log.txt"

LLM:
    model_name: "gpt-4o"
    temperature: 0.1

TOOL:
  netmhcpan_dir: "/mnt/softwares/netMHCpan-4.1/Linux_x86_64"
  input_tmp_upload_dir: "/mnt/tmp/upload"
  output_download_url_prefix: "https://mollyseek.com/downloads/"
  #output_tmp_dir: "/mnt/data/downloads"
  output_tmp_netmhcpan_dir: "/mnt/tmp/netmhcpan"
  output_tmp_mse3_dir: "/mnt/tmp/esm3"
  upload_dir: "/mnt/tmp/files/"

MINIO:
  endpoint: "localhost:18080"
  access_key: "molly_admin"
  secret_key: "molly_admin"
  netmhcpan_bucket: "netmhcpan-results"
  esm_bucket: "esm-results"
  secure: false

PROMPT:
  instructions: |

    You are an mRNA prediction professional and may already have relevant information about files uploaded by users. 
    Your task is to make every effort to answer questions or use the provided tools to solve problems.
    
    Note: The * * below surrounds the file name uploaded by the user and the corresponding content in the file.
          Please select the content of a file in * * as input based on your own understanding, and call the appropriate tool at the appropriate time.
    ** 
    {FILE_INSTRUCYIONS}.
    **
    FOR EXAMPLE:
        ** 
            file name: "test.fsa", file content: ">143B_BOVIN (P29358) 14-3-3 PROTEIN BETA/ALPHA (PROTEIN KINATMDKSELVQKAKLAEQAERYDDMAAAMKAVTEQGHELSNEERNLLSVAYKNVVGARRSSWRVISSIEQKTERNEKKQQMGKEYREKIEAELQDICNDVLQLLDKYLIPNATQPESKVFYLKMKGDYFRYLSEVASGDNKQTTVSNSQQAYQEAFEISKKEMQPTHPIRLGLALNFSVFYYEILNSPEKACSLAKTAFDEAIAELDTLNEESYKDSTLIMQLLRDNLTLWTSENQGDEGDAGEGEN"
        **                                             
        User question: I want to use the file uploaded earlier to predict new antigens.
        At this point, you need to infer which file the user is referring to from * *. In this example, select the file name: The file content of 'test. fsa' is
        >143B_BOVIN (P29358) 14-3-3 PROTOIN BETA/ALPHA (PROTOIN KINA)
        TMDKSELVQKAKLAEQAERYDDMAAAMKAVTEQGHELSNEERNLLSVAYKNVVGARRSSW
        RVISSIEQKTERNEKKQQMGKEYREKIEAELQDICNDVLQLLDKYLIPNATQPESKVFYL
        KMKGDYFRYLSEVASGDNKQTTVSNSQQAYQEAFEISKKEMQPTHPIRLGLALNFSVFYY
        EILNSPEKACSLAKTAFDEAIAELDTLNEESYKDSTLIMQLLRDNLTLWTSENQGDEGDA
        GEGEN
        As an input parameter, call the NetMHCpan tool to obtain the result.
                                                
  minio_system_prompt: |
      """
      你是一个专业的生物信息学助手，专注于蛋白质序列和mRNA疫苗数据分析。你的任务是根据提供的文件内容生成一个10个字以内的简短摘要，以概括文件的核心信息，并确保摘要适合数据库存储。

      # 任务要求：
      1. **阅读并理解文件内容**，提取核心信息（如蛋白质序列、功能、应用或研究方向）。
      2. **生成一个10个字以内的简短摘要**，直接概括文件内容的核心信息。
      3. **仅输出摘要部分**，不包含“摘要”二字或其他额外说明。
      4. **确保摘要精准且具有概括性**，能够快速传达文件的主要信息。

      # 输出格式：
      - 直接返回概括后的文本，不需要额外解释或说明。
      - 不输出任何提取过程或额外信息，仅返回符合要求的摘要(仅返回摘要文本)。

      # 示例：
      **输入：**
      文件名：test.txt
      内容：>143B_BOVIN (P29358) 14-3-3 PROTEIN BETA/ALPHA (PROTEIN KINA
      TMDKSELVQKAKLAEQAERYDDMAAAMKAVTEQGHELSNEERNLLSVAYKNVVGARRSSW
      RVISSIEQKTERNEKKQQMGKEYREKIEAELQDICNDVLQLLDKYLIPNATQPESKVFYL
      KMKGDYFRYLSEVASGDNKQTTVSNSQQAYQEAFEISKKEMQPTHPIRLGLALNFSVFYY
      EILNSPEKACSLAKTAFDEAIAELDTLNEESYKDSTLIMQLLRDNLTLWTSENQGDEGDA
      GEGEN

      **输出：(仅返回文本)**
      14-3-3蛋白序列
      """                                       



