LOGGER:
    level: "DEBUG"
    dir: "./logs/"
    file: "log.txt"

TOOL:
  COMMON:
    output_download_url_prefix: "https://mollyseek.com/downloads/"
  NETMHCPAN:   
    netmhcpan_dir: "/mnt/softwares/netMHCpan-4.1/Linux_x86_64"
    input_tmp_netmhcpan_dir: "/mnt/tmp/NetMHCpan/input"
    output_tmp_netmhcpan_dir: "/mnt/tmp/NetMHCpan/output"
  ESM:
    output_tmp_mse3_dir: "/mnt/tmp/ESM3"
  NETMHCSTABPAN:   
    netmhcstabpan_dir: "/mnt/softwares/netMHCstabpan-1.0/Linux_x86_64"
    input_tmp_netmhcstabpan_dir: "/mnt/tmp/NetMHCstabpan/input"
    output_tmp_netmhcstabpan_dir: "/mnt/tmp/NetMHCstabpan/output"
  PMTNET:
    pMTnet_env_python_dir: "/mnt/softwares/miniconda3/envs/pmtnet/bin/python"
    pMTnet_script_dir: "/mnt/softwares/pMTnet/pMTnet.py"
    library_dir: "/mnt/softwares/pMTnet/library"
    input_tmp_pmtnet_dir: "/mnt/tmp/pMtNet/input"
    output_tmp_pmtnet_dir: "/mnt/tmp/pmtnet/output"
  EXTRACT_PEPTIDE:
    tmp_extract_peptide_dir: "/mnt/tmp/ExtractPeptide/output"
  NETCHOP:
    netchop_dir: "/mnt/softwares/netchop-3.1/Linux_x86_64"
    input_tmp_netchop_dir: "/mnt/tmp/NetChop/input"
    output_tmp_netchop_dir: "/mnt/tmp/NetChop/output"
  PRIME:
    input_tmp_prime_dir: "/mnt/tmp/Prime/input"
    output_tmp_prime_dir: "/mnt/tmp/Prime/output"
  NETTCR:
    nettcr_dir: "/mnt/softwares/NetTCR-2.2"  
    input_tmp_nettcr_dir: "/mnt/tmp/NetTCR/input"
    output_tmp_nettcr_dir: "/mnt/tmp/NetTCR/output"    


 

MINIO:
  endpoint: "localhost:18080"
  netmhcpan_bucket: "netmhcpan-results"
  esm_bucket: "esm3-results"
  netmhcstabpan_bucket: "netmhcstabpan-results"
  pmtnet_bucket: "pmtnet-results"
  extract_peptide_bucket: "extract-peptide-results"
  netchop_bucket: "netchop-results"
  prime_bucket: "prime-results"
  nettcr_bucket: "nettcr-results"
  secure: false
