LOGGER:
    level: "DEBUG"
    dir: "./logs/"
    file: "log.txt"

TOOL:
  COMMON:
    output_download_url_prefix: "https://mollyseek.com/downloads/"
  NETMHCPAN:   
    netmhcpan_dir: "/mnt/softwares/netMHCpan-4.1/Linux_x86_64"
    input_tmp_netmhcpan_dir: "/mnt/tmp/upload"
    output_tmp_netmhcpan_dir: "/mnt/tmp/netmhcpan"
  ESM:
    output_tmp_mse3_dir: "/mnt/tmp/esm3"
 

MINIO:
  endpoint: "localhost:18080"
  access_key: "molly_admin"
  secret_key: "molly_admin"
  netmhcpan_bucket: "netmhcpan-results"
  esm_bucket: "esm-results"
  secure: false

