LOGGER:
    level: "DEBUG"
    dir: "./logs/"
    file: "log.txt"

TOOL:
  COMMON:
    output_download_url_prefix: "https://mollyseek.com/downloads/"
  NETMHCPAN:   
    netmhcpan_dir: "/mnt/softwares/netMHCpan-4.1/Linux_x86_64"
    input_tmp_netmhcpan_dir: "/mnt/tmp/NetMHCpan/input"
    output_tmp_netmhcpan_dir: "/mnt/tmp/NetMHCpan/output"
  ESM:
    output_tmp_mse3_dir: "/mnt/tmp/ESM3"
  NETMHCSTABPAN:   
    netmhcstabpan_dir: "/mnt/softwares/netMHCstabpan-1.0/Linux_x86_64"
    input_tmp_netmhcstabpan_dir: "/mnt/tmp/NetMHCstabpan/input"
    output_tmp_netmhcstabpan_dir: "/mnt/tmp/NetMHCstabpan/output"
  PMTNET:
    pMTnet_env_python_dir: "/mnt/softwares/miniconda3/envs/pmtnet/bin/python"
    pMTnet_script_dir: "/mnt/softwares/pMTnet/pMTnet.py"
    library_dir: "/mnt/softwares/pMTnet/library"
    input_tmp_pmtnet_dir: "/mnt/tmp/pMtNet/input"
    output_tmp_pmtnet_dir: "/mnt/tmp/pmtnet/output"
  EXTRACT_PEPTIDE:
    tmp_extract_peptide_dir: "/mnt/tmp/ExtractPeptide/output"
  NETCHOP:
    netchop_dir: "/mnt/softwares/netchop-3.1/Linux_x86_64"
    input_tmp_netchop_dir: "/mnt/tmp/NetChop/input"
    output_tmp_netchop_dir: "/mnt/tmp/NetChop/output"
  PRIME:
    input_tmp_prime_dir: "/mnt/tmp/Prime/input"
    output_tmp_prime_dir: "/mnt/tmp/Prime/output"
  NETTCR:
    nettcr_dir: "/mnt/softwares/NetTCR-2.2"  
    input_tmp_nettcr_dir: "/mnt/tmp/NetTCR/input"
    output_tmp_nettcr_dir: "/mnt/tmp/NetTCR/output"    
  NETCTLPAN:
    netctlpan_dir: /mnt/softwares/netCTLpan-1.1
    input_tmp_netctlpan_dir: /mnt/tmp/netctlpan/input
    output_tmp_netctlpan_dir: /mnt/tmp/netctlpan/output
  PISTE:
    piste_env_python_dir: /mnt/softwares/miniconda3/envs/piste/bin/python
    input_tmp_piste_dir: /mnt/tmp/piste/input
    output_tmp_piste_dir: /mnt/tmp/piste/output
  IMMUNEAPP:
    script_path: /mnt/softwares/ImmuneApp/ImmuneApp_presentation_prediction.py
    python_bin: /mnt/softwares/miniconda3/envs/ImmuneApp/bin/python
    input_tmp_dir: /mnt/tmp/immuneapp/input  
    output_tmp_dir: /mnt/tmp/immuneapp/output
  IMMUNEAPP_NEO:
    script_path: /mnt/softwares/ImmuneApp/ImmuneApp_immunogenicity_prediction.py
    python_bin: /mnt/softwares/miniconda3/envs/ImmuneApp/bin/python
    input_tmp_dir: /mnt/tmp/immuneapp_neo/input  
    output_tmp_dir: /mnt/tmp/immuneapp_neo/output
  BIGMHC:
    bigmhc_dir: "/mnt/softwares/bigmhc/src"  
    input_tmp_bigmhc_dir: "/mnt/tmp/BigMHC/input"
    output_tmp_bigmhc_dir: "/mnt/tmp/BigMHC/output" 
  TRANSPHLA:
    script_path: /mnt/softwares/TransPHLA-AOMP/TransPHLA-AOMP/pHLAIformer.py
    python_bin: /mnt/softwares/miniconda3/envs/transphla/bin/python
    input_tmp_dir: /mnt/tmp/transphla/input
    output_tmp_dir: /mnt/tmp/transphla/output
  UNIPMT:
    script_path: "/mnt/softwares/UniPMT/code/main.py"
    python_bin: "/mnt/softwares/miniconda3/envs/unipmt/bin/python"
    input_tmp_dir: "/mnt/tmp/UniPMT/input"
    output_tmp_dir: "/mnt/tmp/UniPMT/output"
    nodes_peptides_csv: "/mnt/softwares/UniPMT/data/pmt_pmt/nodes_peptides.csv"
    nodes_mhc_csv: "/mnt/softwares/UniPMT/data/pmt_pmt/nodes_mhc.csv"
    nodes_tcr_csv: "/mnt/softwares/UniPMT/data/pmt_pmt/nodes_tcr.csv"
    p_features_path: "/mnt/softwares/UniPMT/data/pmt_pmt/meta/p_features.npy"
    t_features_path: "/mnt/softwares/UniPMT/data/pmt_pmt/meta/t_features.npy"
    m_features_path: "/mnt/softwares/UniPMT/data/pmt_pmt/meta/m_features.npy"
    unipmt_input_file_path: "/mnt/softwares/UniPMT/data/pmt_pmt/meta"

MINIO:
  endpoint: "localhost:18080"
  netmhcpan_bucket: "netmhcpan-results"
  esm_bucket: "esm3-results"
  netmhcstabpan_bucket: "netmhcstabpan-results"
  pmtnet_bucket: "pmtnet-results"
  extract_peptide_bucket: "extract-peptide-results"
  netchop_bucket: "netchop-results"
  prime_bucket: "prime-results"
  nettcr_bucket: "nettcr-results"
  netctlpan_bucket: "netctlpan-results"
  piste_bucket: "piste-results"
  immuneapp_bucket: "immuneapp-results"
  immuneapp_neo_bucket: "immuneapp-neo-results"
  bigmhc_bucket: "bigmhc-results"
  transphla_bucket: "transphla-results"
  unipmt_bucket: "unipmt-results"
  secure: false
