
import enum
from enum import Enum, IntEnum

class CodeAgentState(Enum):
    NOT_EXIST = "NOT_EXIST"
    WAITING = "WAITING"
    CREATING = "CREATING"
    STARTED = "STARTED"
    GENERATING = "GENERATING"
    EXECUTING = "EXECUTING"
    EVALUATING = "EVALUATING"
    COMPLETE = "COMPLETE"

class ResultCode(IntEnum):
    RESULT_OK = 0x00000000

class CodeGeneratorResultCode(IntEnum):
    RESULT_OK = 0x00000000
    CODE_GENERATE_FAILED = 0x00000011
    ORG_RESULT_CODE_IS_NOT_EXIST = 0x00000012
    ORG_RESULT_CODE_INVITE_FAILED = 0x00000013
    ORG_RESULT_CODE_ADD_FAILED = 0x00000014